[versions]
agp = "8.4.2"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
activityVersion = "1.11.0"
navigationFragment = "2.9.5"
kotlinPlugin = "1.8.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
#mpndroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version = "v3.1.0" }
mapbox-maps = { group = "com.mapbox.maps", name = "android", version = "10.14.0" }
mapbox-sdk-turf = { group = "com.mapbox.mapboxsdk", name = "mapbox-sdk-turf", version = "5.8.0" }
#mapbox-sdk-services= { group = "com.mapbox.mapboxsdk", name = "mapbox-sdk-services", version = "5.9.0" }
mapbox-sdk-services = { group = "com.mapbox.mapboxsdk", name = "mapbox-sdk-services", version = "5.8.0" }
#mapbox-ndk = { group = "com.mapbox.maps", name = "android-ndk27", version = "11.16.2" }

shimmer-facebook-android = { group = "com.facebook.shimmer", name = "shimmer", version = "0.5.0" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version = "1.1.0" }

#okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.11.0" }
#retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
#converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }
#coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }
#coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.7.3" }
#androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.6.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

