name: Android CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

    tags:
      - 'v*'

jobs:

  # -----------------------------------
  # 1️⃣ BUILD JOB
  # -----------------------------------
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build Debug
        run: ./gradlew assembleDebug


  # -----------------------------------
  # 2️⃣ RELEASE JOB (Only Tags)
  # -----------------------------------
  release:
    name: Release APK
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate SemVer
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ ! $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid tag format. Use vX.Y.Z"
            exit 1
          fi
          echo "✅ Valid tag"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Decode keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > keystore.jks
          echo "KEYSTORE_PATH=$(pwd)/keystore.jks" >> $GITHUB_ENV

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Signed Release
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}

      # Generate changelog
      - name: Generate changelog
        run: |
          git fetch --tags
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            echo "First release" > CHANGELOG.txt
          else
            git log $PREV_TAG..HEAD --pretty=format:"- %s" > CHANGELOG.txt
          fi

      # Rename APK
      - name: Rename APK
        id: rename
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk")
          NEW_NAME=WiilRainProject-${TAG}.apk
          mv $APK_PATH $NEW_NAME
          echo "apk_name=$NEW_NAME" >> $GITHUB_OUTPUT

      # Create Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.txt
          files: ${{ steps.rename.outputs.apk_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
